CREATE TABLE Employee (
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	FirstName NVARCHAR(100) NOT NULL, 
	SecondName NVARCHAR(100) NOT NULL, 
	PhoneNumber NVARCHAR(15), 
	EmployeeType NVARCHAR(3) FOREIGN KEY REFERENCES EmployeeType(Code)
)
GO